name: deploy Terraform to AWS
on:
  workflow_dispatch:
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: AWS Client Setup 
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Print Workflow and Repository Name
      run: |
          echo "Actor: ${{ github.actor }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Workspace: ${{ github.workspace }}"

          echo "Repository Name: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }} SHA: ${{ github.sha }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Run Number: ${{ github.run_number }}"
          
    - name: Retrieve AWS S3 bucket name
      run: |
            aws --version
            terraform --version  
            aws s3 ls 


    - name: Terraform Init
      run: | 
          terraform init
          terraform fmt --check 
          terraform validate
          terraform apply -auto-approve
      working-directory: terraform
