name: deploy Terraform to AWS
on:
  workflow_dispatch:

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Terraform Init
      run: terraform init
      #working-directory: ./terraform-aws-mlops

    - name: Print Workflow and Repository Name
      run: |
          echo "Actor: ${{ github.actor }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository Name: ${{ github.repository }}"
          echo "Repository URL: ${{ github.repository_url }}"
          echo "Workflow Path: ${{ github.workflow_path }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Path: ${{ github.event_path }}"

          echo "Workspace: ${{ github.workspace }}"
          echo "Action: ${{ github.action }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Runs URL: ${{ github.runs_url }}"
          echo "Job: ${{ github.job }}"
          echo "Server URL: ${{ github.server_url }}"
          echo "API URL: ${{ github.api_url }}"
          
          echo "Issues URL: ${{ github.issues_url }}"
          echo "Pull Request URL: ${{ github.pull_request_url }}"
          echo "Actions URL: ${{ github.actions_url }}"
          echo "Workflows URL: ${{ github.workflows_url }}"
          echo "Jobs URL: ${{ github.jobs_url }}"
          echo "Artifacts URL: ${{ github.artifacts_url }}"
          echo "Packages URL: ${{ github.packages_url }}"
          echo "Milestones URL: ${{ github.milestones_url }}"
